### PR TITLE
Update depencencies

### PR DESCRIPTION
**Pull request by lukaskollmer**
I ran the tests and there were no issues

### CODE REVIEW

**Comment by maxleiko** [comment]
Hello @lukaskollmer,

Thanks for the PR, checking this right now.

**Comment by maxleiko** [comment]
Ok, the problem is that npm 5 is not compatible with `node v0.12` and the tests are also run against that old version of `node`. So this is not really a big issue.

Concerning your PR, because you bumped `npm` to the new major version `5`, could you also bump the major version of `npmi` to `3.0.0` and update the `README.md` accordingly ?

Thanks

**Comment by maxleiko** [comment]
And yeah, be sure to update the `.travis.yml` so that it does the tests against `node v6` and above (and remove v0.12) :+1:

**Comment by lukaskollmer** [comment]
Done 👍

**Pull request merged**
